#!/usr/bin/env python3
"""Guard the generated http.ts RequestContext against dot-segment path collapse.

encodeURIComponent() does not escape "." (it is unreserved), so a caller-
supplied path-parameter value of exactly "." or ".." survives escaping intact
into the templated URL string. Every generated `*Api.ts` method then hands
that string straight to `RequestContext`'s constructor, which does

    this.url = new URL(ensureAbsoluteUrl(url));

`new URL()` collapses the dot-segment before the request ever reaches
`Middleware.pre()` or `RetryHttpLibrary.send()`, both of which only ever see
the already-collapsed URL, so a guard placed there (the original
#792 priority-1 proposal) can never fire. RequestContext's constructor (and
its unused-but-generated `setUrl` twin) is the only place that still holds
the raw, un-collapsed string, and it is regenerated by `make generate` (it is
not in `.openapi-generator-ignore`), so the guard has to be injected by this
pipeline rather than hand-edited. See #792 and #915 for the full history;
mirrors the Python SDK's `_TypedApiClient.param_serialize` override (#929) at
the equivalent generated chokepoint.

Usage: guard-dot-segment-path.py FILE
Idempotent: an already-guarded file is left alone (and re-validated).
"""

from __future__ import annotations

from pathlib import Path
import sys


GUARD_MARKER = "function assertNoDotSegmentInPath"

ANCHOR = (
    'function ensureAbsoluteUrl(url: string) {\n'
    '    if (url.startsWith("http://") || url.startsWith("https://")) {\n'
    '        return url;\n'
    '    }\n'
    '    return window.location.origin + url;\n'
    '}\n'
)

GUARD_FUNCTION = (
    "\n"
    "// Rejects a literal \".\"/\"..\" path segment before new URL() collapses it (#792, #915).\n"
    "function assertNoDotSegmentInPath(url: string): void {\n"
    "    const path = url.split(/[?#]/, 1)[0];\n"
    "    for (const segment of path.split(\"/\")) {\n"
    "        if (segment === \".\" || segment === \"..\") {\n"
    "            throw new HttpException(`request path contains an unsafe \"${segment}\" segment`);\n"
    "        }\n"
    "    }\n"
    "}\n"
)

CALL_SITE_OLD = "        this.url = new URL(ensureAbsoluteUrl(url));\n"
CALL_SITE_NEW = (
    "        assertNoDotSegmentInPath(url);\n"
    "        this.url = new URL(ensureAbsoluteUrl(url));\n"
)

EXPECTED_CALL_SITES = 2  # RequestContext's constructor and setUrl


def guard_file(path: Path) -> bool:
    source = path.read_text(encoding="utf-8")

    if GUARD_MARKER in source:
        if source.count(CALL_SITE_NEW) != EXPECTED_CALL_SITES:
            raise RuntimeError(
                f"{path}: guard function present but only "
                f"{source.count(CALL_SITE_NEW)}/{EXPECTED_CALL_SITES} call sites are guarded, "
                "generator output shape changed, update this script"
            )
        return False

    call_sites = source.count(CALL_SITE_OLD)
    if call_sites != EXPECTED_CALL_SITES:
        raise RuntimeError(
            f"{path}: expected exactly {EXPECTED_CALL_SITES} unguarded "
            f"'new URL(ensureAbsoluteUrl(url))' call sites (constructor + setUrl), "
            f"found {call_sites}, generator output shape changed, update this script"
        )
    if ANCHOR not in source:
        raise RuntimeError(f"{path}: ensureAbsoluteUrl anchor not found, update this script")

    source = source.replace(CALL_SITE_OLD, CALL_SITE_NEW)
    source = source.replace(ANCHOR, ANCHOR + GUARD_FUNCTION, 1)

    path.write_text(source, encoding="utf-8")
    return True


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print("usage: guard-dot-segment-path.py FILE", file=sys.stderr)
        return 2

    path = Path(argv[0])
    changed = guard_file(path)
    print(f"guard-dot-segment-path: {'guarded' if changed else 'already guarded'} {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
