#!/usr/bin/env bash
# autopilot.sh — set up and manage the autopilot email listener.
#
# Commands:
#   setup    Interactive bootstrap: mint a listener key + forward token, write
#            ~/.e2a-autopilot.env. Does NOT install the service — review the
#            env file, fill in the runtime/workdir fields, then `install`.
#   status   Report config completeness and (if installed) service state.
#   install  Write and load the launchd job (macOS). Refuses if config is
#            incomplete. This is the step that makes autopilot always-on —
#            run it yourself; it is not something an agent should do for you.
#   logs     Tail the running daemon's log.
#   stop     Unload the launchd job (does not delete config).
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$DIR/lib.sh"

ENV_FILE="$HOME/.e2a-autopilot.env"
LAUNCHD_LABEL="dev.e2a.autopilot"
PLIST="$HOME/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
LOG_DIR="$HOME/.e2a-autopilot/logs"

cmd_setup() {
  echo "autopilot setup"
  echo

  a_load_config
  if [ -z "${E2A_API_KEY:-}" ]; then
    echo "No e2a credential found. Run 'e2a login' in a browser (or, headless," \
      "mint an account key at https://e2a.dev/api-keys and 'e2a config set api_key <key>')," \
      "then re-run this."
    exit 1
  fi

  read -rp "Agent inbox to listen on (must already exist, e.g. jace@yourdomain.com): " agent
  [ -z "$agent" ] && { echo "an agent email is required"; exit 1; }

  echo "Minting a least-privilege agent-scoped key for the daemon (separate from any interactive key this agent uses)..."
  key_json="$(a_cli keys create --agent "$agent" --name "autopilot listener — $(date +%Y-%m-%d)" --json)"
  listener_key="$(echo "$key_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["key"])')"

  forward_token="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"

  read -rp "Your (human) email, CC'd on every autopilot reply: " human
  read -rp "Trusted sender allowlist, comma-separated (include your own address and any peer agents): " allowlist
  read -rp "Runtime — claude, codex, or kimi [claude]: " runtime
  runtime="${runtime:-claude}"
  read -rp "Absolute path to the ${runtime} binary (resolve any shim: 'readlink -f \$(which ${runtime})'): " runtime_bin
  read -rp "Working directory for spawned sessions (e.g. ~/Desktop): " workdir
  read -rp "Charter/context file path spawned sessions should read first (optional, blank to skip): " charter
  settings=""
  if [ "$runtime" = "claude" ]; then
    read -rp "Path to a sandboxed headless settings.json (see headless-settings.claude.example.json; blank = none, NOT recommended): " settings
  fi

  cat > "$ENV_FILE" <<EOF
# e2a autopilot — generated by autopilot.sh setup on $(date -u +%FT%TZ)
export E2A_API_KEY="$listener_key"
export E2A_AGENT_EMAIL="$agent"
export E2A_AUTOPILOT_FORWARD_TOKEN="$forward_token"
export E2A_AUTOPILOT_ALLOWLIST="$allowlist"
export E2A_AUTOPILOT_HUMAN="$human"
export E2A_AUTOPILOT_RUNTIME="$runtime"
export E2A_AUTOPILOT_RUNTIME_BIN="$runtime_bin"
export E2A_AUTOPILOT_WORKDIR="$workdir"
export E2A_AUTOPILOT_CHARTER="$charter"
export E2A_AUTOPILOT_SETTINGS="$settings"
export E2A_AUTOPILOT_PORT="8991"
EOF
  chmod 600 "$ENV_FILE"
  echo
  echo "Wrote $ENV_FILE (mode 600)."
  echo "Review it, then run: $0 install"
}

cmd_status() {
  a_load_config
  if a_config_ok; then
    echo "config: OK (agent $E2A_AGENT_EMAIL, runtime $E2A_AUTOPILOT_RUNTIME)"
  else
    echo "config: MISSING or incomplete — run: $0 setup"
    return
  fi
  if launchctl print "gui/$(id -u)/${LAUNCHD_LABEL}" >/dev/null 2>&1; then
    echo "service: running"
    launchctl print "gui/$(id -u)/${LAUNCHD_LABEL}" | grep -E "state|pid" || true
  else
    echo "service: not installed — run: $0 install"
  fi
}

cmd_install() {
  a_load_config
  if ! a_config_ok; then
    echo "config incomplete — run: $0 setup" >&2
    exit 1
  fi
  local node_bin
  node_bin="$(command -v node)"
  mkdir -p "$LOG_DIR"

  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${node_bin}</string>
    <string>${DIR}/runner.mjs</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>E2A_API_KEY</key><string>${E2A_API_KEY}</string>
    <key>E2A_AGENT_EMAIL</key><string>${E2A_AGENT_EMAIL}</string>
    <key>E2A_AUTOPILOT_FORWARD_TOKEN</key><string>${E2A_AUTOPILOT_FORWARD_TOKEN}</string>
    <key>E2A_AUTOPILOT_ALLOWLIST</key><string>${E2A_AUTOPILOT_ALLOWLIST}</string>
    <key>E2A_AUTOPILOT_HUMAN</key><string>${E2A_AUTOPILOT_HUMAN}</string>
    <key>E2A_AUTOPILOT_RUNTIME</key><string>${E2A_AUTOPILOT_RUNTIME}</string>
    <key>E2A_AUTOPILOT_RUNTIME_BIN</key><string>${E2A_AUTOPILOT_RUNTIME_BIN}</string>
    <key>E2A_AUTOPILOT_WORKDIR</key><string>${E2A_AUTOPILOT_WORKDIR}</string>
    <key>E2A_AUTOPILOT_CHARTER</key><string>${E2A_AUTOPILOT_CHARTER:-}</string>
    <key>E2A_AUTOPILOT_SETTINGS</key><string>${E2A_AUTOPILOT_SETTINGS:-}</string>
    <key>E2A_AUTOPILOT_PORT</key><string>${E2A_AUTOPILOT_PORT:-8991}</string>
    <key>E2A_URL</key><string>${E2A_URL:-https://e2a.dev}</string>
    <key>PATH</key><string>/usr/local/bin:/opt/homebrew/bin:$(dirname "$node_bin"):/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>StandardOutPath</key><string>${LOG_DIR}/autopilot.log</string>
  <key>StandardErrorPath</key><string>${LOG_DIR}/autopilot.err.log</string>
</dict>
</plist>
EOF

  launchctl bootout "gui/$(id -u)/${LAUNCHD_LABEL}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST"
  sleep 2
  echo "Installed. Status:"
  cmd_status
  echo
  echo "Log: $LOG_DIR/autopilot.log — tail it now with: $0 logs"
  echo "Send a real test email next (see SKILL.md Verification)."
}

cmd_logs() {
  tail -f "$LOG_DIR/autopilot.log" "$LOG_DIR/autopilot.err.log" 2>/dev/null
}

cmd_stop() {
  launchctl bootout "gui/$(id -u)/${LAUNCHD_LABEL}" 2>/dev/null \
    && echo "stopped" || echo "was not running"
}

case "${1:-}" in
  setup) cmd_setup ;;
  status) cmd_status ;;
  install) cmd_install ;;
  logs) cmd_logs ;;
  stop) cmd_stop ;;
  *)
    echo "usage: $0 [setup|status|install|logs|stop]" >&2
    exit 2
    ;;
esac
