import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Jest coverage reports (generated by `jest --coverage`).
    "coverage/**",
  ]),
  // Two React 19 strict rules from eslint-plugin-react-hooks are
  // over-eager for legitimate "now-ish" UI and prop→state sync
  // patterns we use across the dashboard:
  //
  //   • react-hooks/purity flags `Date.now()` calls inside render /
  //     useMemo even when the result is intentionally refreshed via
  //     a tick dep (e.g. "expires in 47m" labels on the pending
  //     queue, the "indexed Ns ago" line on the dashboard overview).
  //   • react-hooks/set-state-in-effect flags useEffects that reset
  //     local state when a prop changes — a documented React idiom
  //     for component-level state that derives from a prop key (here:
  //     PendingDetailPanel re-locking the form when messageId moves).
  //
  // Both rules also fire nondeterministically depending on which
  // patch version of eslint-plugin-react-hooks `npm install` resolves
  // (the repo has no lockfile). Pinning the plugin in package.json
  // would be a heavier change; disabling these two rules globally
  // keeps CI deterministic while we wait for stable upstream
  // semantics.
  {
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
